### ISSUE TITLE
As a ReactJS underpart

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi-js-wrapper#20]
Hey,

shouldnt this work as a part of ReactJS?

Like when I just `npm i pokeapi-js-wrapper --save` and then try to import it, it errors out. I would love to have this working, because I'm not familiar with service worker, so yea.

`Could not find a declaration file for module 'pokeapi-js-wrapper'. 'node_modules/pokeapi-js-wrapper/dist/index.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/pokeapi-js-wrapper if it exists or add a new declaration (.d.ts) file containing declare module 'pokeapi-js-wrapper';ts(7016)`

**Comment by LuziferSenpai** [comment]
Nop, I'm in the app directory. It still shows the error.

**Comment by LuziferSenpai** [comment]
I just deleted it out of the link above, because of privat data

**Comment by Naramsim** [comment]
The error you posted has nothing to do with reactjs. It's about Typescript types. We don't offer any types yet.

**Comment by LuziferSenpai** [comment]
Then it doesnt make sense to have a npm packet. They always need that. Even in my basic node project it errors with that.

**Comment by LuziferSenpai** [comment]
Okay, this issue is fixed somehow.

**Comment by Naramsim** [comment]
Npm is a Javascript registry. Millions of people are using Javascript for their projects.
