### ISSUE TITLE
Service Worker installation failed

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi-js-wrapper#21]
Hey,

I got this error when npm starting my ReactJS Project.

`OMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/pokeapi-js-wrapper-sw.js'): The script has an unsupported MIME type ('text/html').`

```js
const Pokedex = require("pokeapi-js-wrapper")

const P = new Pokedex.Pokedex({cacheImages: true})
```

**Comment by Naramsim** [comment]
Your webserver is adding the wrong MIME type to the response. I suggest you to not add any MIME type or add a correct one (`text/javascript`).

Read more on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript
