### ISSUE TITLE
A catch that fetches without / at the end

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi-js-wrapper#22]
Hey,

it would be nice if there would be a catch after the first fetch, that excludes the / at the end of the fetch url.

Because that causes problems for me since the first minute.

Greetz,

Luzifer

**Comment by Naramsim** [comment]
Hi, let me understand.

Do you want to add a `.catch()` immediately after the `.fetch()`? 

Isn't it already there?

https://github.com/PokeAPI/pokeapi-js-wrapper/blob/739a393e58d3d251b6897372a11b5075584a70ec/src/getter.js#L52

**Comment by LuziferSenpai** [comment]
But it doesnt retry to fetch without the / at the end ;)

Am So., 21. März 2021 um 21:57 Uhr schrieb Alessandro Pezzè <
***@***.***>:

**Comment by LuziferSenpai** [comment]
But it doesnt retry the fetch without the / at the end

**Comment by Naramsim** [comment]
Ahh, you want the retry! Now I understand

**Comment by LuziferSenpai** [comment]
Yea, because of I get ALOT of errors that it cant fetch the url with / at the end, when I then open it, it errors too, but when I remove the / it works.

**Comment by Naramsim** [comment]
I can think about it. I don't have much time though. Don't expect something quick from my side

**Comment by shinymimiq** [comment]
Proposed a PR for it. #25

**Comment by Phoenix-Starlight** [comment]
I'm experiencing this issue again, where dropping the slash fixes it. It occurs specifically at this URL `https://pokeapi.co/api/v2/pokemon/218/` but not any URL before index 218.

**Comment by Naramsim** [comment]
hmm, by browsing the URL without the final `/` you see something	?

**Comment by Phoenix-Starlight** [comment]
Via the wrapper I do get an object corresponding to the correct data, but if I do not then I simply get `''`. Browsing through the browser has the JSON display.
