### ISSUE TITLE
1.2.1 release

### ISSUE THREAD

**Issue by goodevilgenius** [PokeAPI/pokeapi-js-wrapper#31]
The latest version on npm is 1.2.0. But the version in master is marked as 1.2.1. There have been some additional routes added since then. Just wondering when 1.2.1 will be released.

**Comment by Naramsim** [comment]
Oupsie, my bad. I'll try this afternoon.

**Comment by Naramsim** [comment]
I've published 1.2.2

Can you test if everything works fine?
