### ISSUE TITLE
Update Usage to module syntax

### ISSUE THREAD

**Issue by beingbrown** [PokeAPI/pokeapi-js-wrapper#5]
I wonder if there's not an option to update or add the usage syntax:

```
import {Pokedex} from 'pokeapi-js-wrapper';

const dex = new Pokedex();
```

I'd be happy to draft a PR if desired.

**Comment by Naramsim** [comment]
Can you create a jsfiddle or add it to the tests?

**Comment by beingbrown** [comment]
Sure--let me see what I can whip up.

**Comment by Naramsim** [comment]
Closing since we got no answer
